DefGuard/defguard

- docker-compose.yaml
- e2e/pnpm-lock.yaml
- e2e/tests/auth.spec.ts
- e2e/tests/openid.spec.ts
- e2e/utils/controllers/acceptRecovery.ts
- e2e/utils/controllers/mfa/enableTOTP.ts
- e2e/utils/waitForRoute.ts
- src/handlers/auth.rs
- tests/auth.rs
- web/pnpm-lock.yaml
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetails.tsx
fix: remove active session when accepting recovery codes
fix: destroy session upon accepting recovery codes and enabling mfa
> test: openid flow

- e2e/config.ts
- e2e/tests/auth.spec.ts
- e2e/tests/openid.spec.ts
- e2e/utils/controllers/createUser.ts
- e2e/utils/controllers/login.ts
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UserProfile/UserProfile.tsx
- web/src/shared/components/layout/Select/Select.tsx
test: admin account totp
chore: create user helper with groups option
> test: recovery codes e2e

- src/handlers/mod.rs
- src/handlers/user.rs
- src/lib.rs
- tests/user.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/users/UserProfile/UserAuthInfo/UserAuthInfo.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/UserAuthInfoPassword.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/ChangeSelfPasswordModal/ChangeSelfPasswordModal.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/ChangeSelfPasswordModal/components/ChangeSelfPasswordForm.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/ChangeSelfPasswordModal/hooks/useChangeSelfPasswordModal.ts
- web/src/pages/users/UsersOverview/modals/AddUserModal/AddUserForm.tsx
- web/src/shared/hooks/useApi.tsx
- web/src/shared/types.ts
fix: username validation in add user form
> feat: change self password

- src/handlers/user.rs
- web/src/components/App/App.tsx
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/auth/AuthPage.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/ChangeSelfPasswordModal/components/ChangeSelfPasswordForm.tsx
- web/src/pages/users/UserProfile/UserDevices/DeviceCard/DeviceCard.tsx
- web/src/pages/users/UserProfile/UserDevices/DeviceCard/style.scss
- web/src/pages/users/UserProfile/UserDevices/modals/UserDeviceModal/UserDeviceModal.tsx
- web/src/pages/users/UserProfile/UserDevices/modals/UserDeviceModal/steps/ConfigStep.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/AddUserForm.tsx
- web/src/pages/users/shared/modals/ChangeUserPasswordModal/ChangePasswordForm.tsx
- web/src/shared/components/Router/Guards/ProtectedRoute/ProtectedRoute.tsx
- web/src/shared/validators/password.ts
- fix: device card info
- fix: router guard
- fix: login redirect when wireguard module disabled
- chore: password validation moved to helper function
- chore: password length increased to max 128
> chore: web fixes

- Cargo.lock
- Cargo.toml
- migrations/20230725115257_wireguard_stats_purge.down.sql
- migrations/20230725115257_wireguard_stats_purge.up.sql
- sqlx-data.json
- src/bin/defguard.rs
- src/config.rs
- src/grpc/mod.rs
- src/lib.rs
- src/wireguard_stats_purge.rs
Enable periodically purging stats records older than a set value.
> feat: purge wireguard stats

- migrations/20230728091355_enrollment.up.sql
- sqlx-data.json
- src/db/models/enrollment.rs
- src/db/models/mod.rs
- src/db/models/settings.rs
- src/error.rs
- src/grpc/enrollment.rs
- src/handlers/mod.rs
- src/handlers/user.rs
- src/wireguard_stats_purge.rs
- tests/enrollment.rs
- tests/user.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/users/UsersOverview/UsersOverview.tsx
- web/src/pages/users/UsersOverview/components/UserEditButton/UserEditButton.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/AddUserForm.tsx
- web/src/pages/users/UsersOverview/modals/StartEnrollmentModal/StartEnrollmentForm.tsx
- web/src/pages/users/UsersOverview/modals/StartEnrollmentModal/StartEnrollmentModal.tsx
- web/src/shared/hooks/store/useModalStore.ts
- web/src/shared/hooks/useApi.tsx
- web/src/shared/types.ts
- add optional enrollment email to token
- don't trigger enrollment automatically on user creation
- fix welcome message content
- wrap enrollment endpoints in DB transactions
> fix: enrollment start fixes

- Cargo.lock
- Cargo.toml
- migrations/20230728091355_enrollment.down.sql
- migrations/20230728091355_enrollment.up.sql
- sqlx-data.json
- src/bin/defguard.rs
- src/config.rs
- src/db/models/enrollment.rs
- src/db/models/settings.rs
- src/error.rs
- src/grpc/enrollment.rs
- src/lib.rs
- src/templates.rs
- tests/settings.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/settings/EnrollmentTab/EnrollmentTab.tsx
- web/src/pages/settings/EnrollmentTab/styles.scss
- web/src/shared/types.ts
- add default message content
- add template tags in messages
- add configurable email subject
> feat: enrollment messaging updates

- Cargo.lock
- Cargo.toml
- model-derive/Cargo.toml
- model-derive/src/lib.rs
- sqlx-data.json
- src/db/models/settings.rs
- src/db/models/wallet.rs
- src/handlers/wireguard.rs
- tests/auth.rs
- tests/common/mod.rs
- tests/user.rs
* Use syn 2.0
* Generate database queries for `SecretString`
> feat: update model-derive to handle SecretString

- src/bin/defguard.rs
- src/config.rs
- src/lib.rs
This subcommand is meant to be used in automated defguard instance setup.
> feat: add subcommand to initialize first VPN location

- src/templates.rs
- templates/base.tera
- templates/macros.tera
- templates/mail_desktop_start.tera
- templates/mail_desktop_start.tpl
- templates/mail_enrollment_admin_notification.tera
- templates/mail_enrollment_admin_notification.tpl
- templates/mail_enrollment_start.tera
- templates/mail_enrollment_welcome.tera
- templates/mail_support_data.tera
- templates/mail_support_data.tpl
- templates/mail_test.tera
move mjml code to tera macros in order to make email templates more about actual content than HTML tables hell.
> feat: email templates macros

- web/src/pages/openid/modals/OpenIdClientModal/OpenIdClientModalForm.tsx
> fix: remove redirect url validation in oidc form

- .github/workflows/current.yml
- Cargo.lock
Disable building ARM images due to significant issues with QEMU performance.
> ci: disable ARM image builds

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- e2e/tests/auth.spec.ts
- src/auth/mod.rs
- src/db/models/wallet.rs
- templates/mail_email_mfa_activation.tera
- templates/mail_email_mfa_code.tera
- tests/auth.rs
- tests/user.rs
Shorten token validity to 1 minute.
> fix: adjust email token validity period

- Cargo.lock
- Cargo.toml
- src/handlers/user.rs
- tests/auth.rs
- tests/user.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/AddUserForm.tsx
- web/src/shared/patterns.ts
Allow LDAP-compatible usernames
> fix: allow username special chars

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/network/NetworkEditForm/NetworkEditForm.tsx
- web/src/pages/settings/components/SmtpSettings/components/SmtpSettingsForm/SmtpSettingsForm.tsx
- web/src/pages/wizard/components/WizardMapDevices/WizardMapDevices.tsx
- web/src/pages/wizard/components/WizardNetworkConfiguration/WizardNetworkConfiguration.tsx
- web/src/shared/validators.ts
fixes forms that use zod.number() in schema
> fix: handle native numbers in form inputs

- .github/workflows/ci.yml
- src/db/models/enrollment.rs
> fix: allow enrollment session continuation

- .sqlx/query-d430472056fd352f9d43a3d9d259e00a74aacc38dfca073908281742a315cf06.json
- migrations/20240318113507_auth_key_constraint.down.sql
- migrations/20240318113507_auth_key_constraint.up.sql
- src/handlers/ssh_authorized_keys.rs
> Allow multiple users to use the same ssh/gpg authentication public key

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
> typo: SSH, not SHH, fix #617

- src/db/models/device.rs
The issue is described in more detail in #636 
fixes #636
> fix: make config structure valid if some fields are missing

- src/handlers/auth.rs
The issue has been described in more detail in #643  
fixes #643
> fix: invalidate all user sessions when MFA is enabled

- Cargo.lock
- Cargo.toml
> Bump version 0.10.0 -> 0.11.0

- docker-compose.yaml
- templates/base.tera
> update defguard logo in email template

- .github/workflows/ci.yml
- .github/workflows/current.yml
- .github/workflows/dev-deployment.yml
- .github/workflows/docs.yml
- .github/workflows/e2e.yml
- .github/workflows/lint-e2e.yml
- .github/workflows/lint-web.yml
Updates all actions except for the release action which requires a bigger rework.
> Update actions to use the correct runner

- src/enterprise/handlers/mod.rs
- src/enterprise/license.rs
- web/src/components/AppLoader.tsx
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/auth/AuthPage.tsx
- web/src/pages/auth/Login/Login.tsx
- web/src/pages/settings/components/EnterpriseSettings/EnterpriseSettings.tsx
- web/src/pages/settings/components/GlobalSettings/components/LicenseSettings/LicenseSettings.tsx
- web/src/pages/settings/components/GlobalSettings/components/LicenseSettings/styles.scss
- web/src/pages/settings/components/OpenIdSettings/OpenIdSettings.tsx
- web/src/pages/settings/components/OpenIdSettings/components/OpenIdGeneralSettings.tsx
- web/src/pages/settings/components/OpenIdSettings/components/OpenIdSettingsForm.tsx
- web/src/shared/hooks/store/useAppStore.ts
- web/src/shared/types.ts
> Display license info on the settings page

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsWarningModals.tsx
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/hooks/useProfileDetailsWarningModal.tsx
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/style.scss
> Display warning modal when trying to change the username or email

- web/src/shared/validators.ts
> fix: Fix dns input

- .github/workflows/build-docker.yml
Build Docker images for ARMv7 32bit architecture.
> feat(CI): enable armv7 docker builds

- web/src/pages/users/UserProfile/UserDevices/UserDevices.tsx
> fix device management by admins

- Cargo.lock
- src/handlers/user.rs
- web/src/pages/auth/Login/Login.tsx
- web/src/pages/network/NetworkGateway/NetworkGateway.tsx
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/AddUserForm.tsx
- web/src/shared/patterns.ts
> Lower username limit to minimum 1 character

- e2e/config.ts
- e2e/tests/vpn/networkdevice.spec.ts
- e2e/types.ts
- e2e/utils/controllers/vpn/createNetworkDevice.ts
> Network devices e2e tests

- Cargo.lock
- Cargo.toml
- src/enterprise/directory_sync/google.rs
- src/enterprise/directory_sync/microsoft.rs
- src/enterprise/directory_sync/mod.rs
- web/src/pages/settings/components/OpenIdSettings/components/DirectorySyncSettings.tsx
- web/src/pages/settings/components/OpenIdSettings/components/OpenIdSettingsRootForm.tsx
> Microsoft OIDC sync

- src/db/models/settings.rs
- tests/auth.rs
Closes https://github.com/DefGuard/defguard/issues/978
> Allow using SMTP servers without authentication

- web/src/pages/devices/modals/StandaloneDeviceConfigModal/StandaloneDeviceConfigModal.tsx
- web/src/pages/users/UserProfile/UserAuthenticationKeys/AuthenticationKeyList/AuthenticationKeyItemYubiKey/AuthenticationKeyItemYubiKey.tsx
- web/src/pages/users/shared/modals/RenameApiTokenModal/RenameApiTokenModal.tsx
- web/src/pages/users/shared/modals/RenameAuthenticationKeyModal/RenameAuthenticationKeyModal.tsx
- web/src/shared/scss/global/_index.scss
Additional cleanup PR for https://github.com/DefGuard/defguard/pull/992 since apparently the linter did not catch invalid imports.
> chore: remove empty SCSS files pt. 2

- migrations/20250213094023_acl.down.sql
- migrations/20250213094023_acl.up.sql
- src/db/models/group.rs
- src/enterprise/db/models/acl.rs
- src/enterprise/db/models/mod.rs
> DB model for ACL functionality

- Cargo.lock
- Cargo.toml
- src/db/models/device.rs
- src/db/models/wireguard.rs
- src/grpc/mod.rs
- src/handlers/group.rs
- src/handlers/user.rs
- src/handlers/wireguard.rs
- src/lib.rs
- add documentations for network-related endpoint
- add security schema definition
> Update REST API docs

- web/src/pages/users/UserProfile/style.scss
Adjust CSS grid row height to put tokens right under auth keys.
> fix user profile page layout on wide screens

- .sqlx/query-0d0ed874821849ae07a9f49f17600b2a4cbedb33babd5b9fc908ec17d3f882e2.json
- .sqlx/query-0d16965b4248d7297b92c0d14ded508dbd1407c8963b3fb240ad24b84fdf5fab.json
- .sqlx/query-406d99b05beaa7cbd8554aadd7a16ceb4e139f131e33a032dd4b719a937de935.json
- .sqlx/query-5e304fafd2e6b526042c2f43e038f6464ef320242782b486f7e17c7742eec1f0.json
- .sqlx/query-9564c6bf55964238003a93c4047ea956656c9ef58f46ede7bc8225900ade4579.json
- .sqlx/query-b84b09a440fab66250603e50a3080fc67194a7de7cf7241d938b25f068525411.json
- .sqlx/query-d2c2173b83c2948b01c2571c5a929a3c89e0725d2d2d7a1aa6739f1870a4fd05.json
- Cargo.lock
- Cargo.toml
- migrations/20250228101233_directory_sync_group_match.down.sql
- migrations/20250228101233_directory_sync_group_match.up.sql
- src/enterprise/db/models/openid_provider.rs
- src/enterprise/directory_sync/microsoft.rs
- src/enterprise/directory_sync/mod.rs
- src/enterprise/handlers/api_tokens.rs
- src/enterprise/handlers/openid_login.rs
- src/enterprise/handlers/openid_providers.rs
- tests/openid_login.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/settings/components/OpenIdSettings/components/DirectorySyncSettings.tsx
- web/src/pages/settings/components/OpenIdSettings/components/OpenIdSettingsRootForm.tsx
- web/src/shared/types.ts
- adds option to specify groups to sync
- fixes issues with syncing groups on login
> Microsoft group sync changes

- web/src/pages/acl/AclCreatePage/AclCreatePage.tsx
- web/src/pages/acl/AclCreatePage/components/DialogSelect/DialogSelectModal/style.scss
- web/src/pages/acl/AclCreatePage/components/DialogSelect/style.scss
- web/src/shared/utils/removeEmptyStrings.ts
1. allow ports field to be an empty string
2. fix gradient positioning in dialogselect track
3. fix dialogselect options list having overflow of hidden
4. fix incorrect translation error in ports validation chain
5. change never expires checkbox to set expires value to explicit null when changed to "checked" state.
> acl form fixes

- src/enterprise/db/models/acl.rs
- src/enterprise/firewall.rs
Implement stuff related to ACL drafts etc that was left as TODO in initial implementation.
> Fix firewall todos

- migrations/20250320104446_acl_allow_conflicting_sources.down.sql
- migrations/20250320104446_acl_allow_conflicting_sources.up.sql
- src/enterprise/db/models/acl.rs
Allow ACL rules with sources that appear as both allow and deny:
- users
- groups
- devices
> Acl allow conflicting sources

- web/src/pages/acl/AclCreatePage/AclCreatePage.tsx
- web/src/pages/acl/AclCreatePage/style.scss
- web/src/pages/acl/AclIndexPage/components/AclIndexAliases/modals/AlcAliasCEModal/AlcAliasCEModal.tsx
- web/src/pages/acl/validators.ts
* Add validator for ACL destination field
* Mark locations with disabled acl with gray icon
> ACL frontend fixes and tweaks

- src/enterprise/firewall.rs
Fixes issue where duplicate firewall rules were generated from ACLs.
> duplicate ACL rule fix

- web/src/pages/acl/AclCreatePage/AclCreatePage.tsx
Fixes issues with revalidating related fields in certain situations.
> fix ACL form validation

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- flake.lock
- model-derive/LICENSE.md
- src/enterprise/handlers/openid_login.rs
- src/enterprise/ldap/model.rs
- src/handlers/openid_flow.rs
- tests/openid.rs
- setup cargo audit workflow
- migrate to `openidconnect` 4.0: https://github.com/ramosbugs/openidconnect-rs/blob/main/UPGRADE.md
> add cargo audit workflow to CI

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- flake.lock
- src/config.rs
- src/db/mod.rs
- src/db/models/device.rs
- src/db/models/group.rs
- src/db/models/mod.rs
- src/db/models/user.rs
- src/db/models/wireguard.rs
- src/enterprise/db/models/acl.rs
- src/enterprise/directory_sync/mod.rs
- src/enterprise/firewall.rs
- src/enterprise/ldap/sync.rs
- src/enterprise/limits.rs
- src/globals.rs
- tests/integration/acl.rs
closes https://github.com/DefGuard/defguard/issues/1101
> run integration tests in CI using cargo-nextest

- src/handlers/wireguard.rs
- tests/integration/wireguard.rs
resolves https://github.com/DefGuard/defguard/issues/1141
> always parse allowed IPs as network addresses

- flake.lock
- src/enterprise/firewall.rs
- src/lib.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/ko/index.ts
- web/src/i18n/pl/index.ts
Backport hotfix for ACLs introduced in https://github.com/DefGuard/defguard/pull/1157
> backport ACL hotfix from 1.3.1

- src/config.rs
- src/lib.rs
This is the same as https://github.com/DefGuard/defguard/pull/1164 but with minor changes regarding how the VPN network is saved.
> Change init vpn command behavior

- crates/defguard_core/src/config.rs
- crates/defguard_core/src/enterprise/ldap/mod.rs
- crates/defguard_core/src/enterprise/ldap/sync.rs
- crates/defguard_core/src/grpc/mod.rs
- crates/defguard_core/src/lib.rs
As requested by a client.
closes #1254
> Allow binding to a specific address

- crates/defguard_core/src/db/models/authentication_key.rs
- crates/defguard_core/src/handlers/ssh_authorized_keys.rs
> Fix auth key delete endpoint

- e2e/tests/auth.spec.ts
fixes e2e that test if user stops being authorized when admin disables him during valid session
> fix logout when disabled e2e test

- crates/defguard_core/src/db/models/wireguard.rs
- crates/defguard_core/tests/integration/common/mod.rs
- crates/defguard_core/tests/integration/wireguard.rs
- crates/defguard_core/tests/integration/wireguard_network_allowed_groups.rs
- crates/defguard_core/tests/integration/wireguard_network_devices.rs
- migrations/20250730141806_higher_peer_disconnect_threshold.down.sql
- migrations/20250730141806_higher_peer_disconnect_threshold.up.sql
- web/src/pages/network/NetworkEditForm/NetworkEditForm.tsx
- web/src/pages/wizard/hooks/useWizardStore.ts
Updates peer disconnect threshold to 5 minutes.
> change default peer disconnect threshold to 300

- README.md
⚠︎ If the checkbox will not be confirmed - we can't include your contribution in our codebase.
> Enterprise link is 404

- crates/defguard_core/src/version.rs
- crates/defguard_version/src/lib.rs
- crates/defguard_version/src/server.rs
Fixes version comparison by omitting build metadata.
> Fix version comparison

- web/src/pages/acl/AclIndexPage/components/AclIndexAliases/modals/AlcAliasCEModal/AlcAliasCEModal.tsx
- web/src/pages/addDevice/steps/AddDeviceSetupStep/AddDeviceSetupStep.tsx
- web/src/pages/auth/Login/Login.tsx
- web/src/pages/auth/MFARoute/MFAEmail/MFAEmail.tsx
- web/src/pages/auth/MFARoute/MFATOTPAuth/MFATOTPAuth.tsx
- web/src/pages/devices/modals/components/StandaloneDeviceModalForm/formSchema.ts
- web/src/pages/groups/components/modals/AddGroupModal/AddGroupModal.tsx
- web/src/pages/network/NetworkEditForm/NetworkEditForm.tsx
- web/src/pages/openid/modals/OpenIdClientModal/OpenIdClientModalForm.tsx
- web/src/pages/settings/components/ActivityLogStreamSettings/modals/LogStashHttpStreamCEModal/LogStashHttpStreamCEModal.tsx
- web/src/pages/settings/components/ActivityLogStreamSettings/modals/VectorHttpStreamCEModal/VectorHttpStreamCEModal.tsx
- web/src/pages/settings/components/GlobalSettings/types.ts
- web/src/pages/settings/components/LdapSettings/components/LdapSettingsForm.tsx
- web/src/pages/settings/components/SmtpSettings/components/SmtpSettingsForm/SmtpSettingsForm.tsx
- web/src/pages/settings/components/SmtpSettings/components/SmtpTest/SmtpTest.tsx
- web/src/pages/settings/components/SmtpSettings/components/SmtpTest/SmtpTestModal.tsx
- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/ManageWebAuthNModal/components/RegisterWebAuthNForm.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/RegisterEmailMFAModal/components/RegisterMFAEmailForm/RegisterMFAEmailForm.tsx
- web/src/pages/users/UserProfile/UserAuthInfo/modals/RegisterTOTPModal/RegisterTOTPModal.tsx
- web/src/pages/users/UserProfile/UserDevices/modals/EditUserDeviceModal/UserDeviceEditForm.tsx
- web/src/pages/users/shared/modals/AddApiTokenModal/components/AddApiTokenForm/AddApiTokenForm.tsx
- web/src/pages/users/shared/modals/AddAuthenticationKeyModal/components/AddAuthenticationKeyForm/AddAuthenticationKeyForm.tsx
- web/src/pages/users/shared/modals/RenameApiTokenModal/RenameApiTokenModal.tsx
- web/src/pages/users/shared/modals/RenameAuthenticationKeyModal/RenameAuthenticationKeyModal.tsx
- web/src/pages/wizard/components/WizardMapDevices/types.ts
- web/src/pages/wizard/components/WizardNetworkConfiguration/WizardNetworkConfiguration.tsx
- web/src/pages/wizard/components/WizardNetworkImport/WizardNetworkImport.tsx
- web/src/shared/components/Layout/EnterpriseUpgradeToast/types.ts
- web/src/shared/components/Layout/VersionUpdateToast/types.ts
> add trim to string fields in zod schemas

- .github/workflows/release.yml
Update node and remove failing cache setup
> chore(CI): update node version in release workflow

- web/src/pages/users/UserProfile/ProfileDetails/ProfileDetailsForm/ProfileDetailsForm.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/AddUserForm.tsx
User forms shouldn't send empty strings when phone number is not provided.
Related issue: https://github.com/DefGuard/defguard/issues/1582
> Don't send empty strings when phone number is not provided
