DefGuard/defguard

- .gitignore
- web/src/pages/network/NetworkEditForm/NetworkEditForm.tsx
Actually show the allowed groups that are assigned to a location in Web UI.
> fix: show configured allowed groups in location edit form

- src/grpc/enrollment.rs
- src/handlers/mail.rs
- src/handlers/user.rs
- src/handlers/wireguard.rs
- src/templates.rs
- tests/user.rs
Remove session info from emails triggered by admin actions.
> fix: remove device data from admin emails

- .sqlx/query-92c38d7487d3aa5342fbe4d059cb073400544f1ce454d059ac13b24b32cbdbf4.json
- src/auth/mod.rs
- src/db/models/device.rs
- src/db/models/group.rs
- src/db/models/wireguard.rs
- src/grpc/desktop_client_mfa.rs
- src/grpc/enrollment.rs
- src/grpc/mod.rs
- src/handlers/auth.rs
- src/handlers/mail.rs
- src/handlers/user.rs
- src/handlers/wireguard.rs
- src/templates.rs
- src/wireguard_peer_disconnect.rs
- tests/wireguard_network_import.rs
Implements gRPC endpoints necessary for desktop client MFA.
> feat: desktop client MFA

- .sqlx/query-63dd22326d77a452d5624d378b0653a7b6b98d71caaf55c6651a44bbd57df017.json
- src/db/models/device.rs
- src/db/models/wireguard.rs
- src/grpc/desktop_client_mfa.rs
- src/grpc/gateway.rs
- src/handlers/wireguard.rs
- src/wireguard_peer_disconnect.rs
Prevent sending unauthorized peer to MFA-enabled location's gateway when adding a new device.
> fix: invalid new MFA peer

- src/config.rs
- src/handlers/auth.rs
Rename `DEFGUARD_AUTH_SESSION_LIFETIME` to `DEFGUARD_AUTH_COOKIE_TIMEOUT` and change it's type to humantime::Duration to be consistent with other timeout options.
> Auth cookie lifetime option

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/addDevice/steps/AddDeviceConfigStep/AddDeviceConfigStep.tsx
- web/src/pages/users/UserProfile/UserDevices/DeviceCard/DeviceCard.tsx
- web/src/pages/users/UserProfile/UserDevices/UserDevices.tsx
When all networks assigned to groups and the user has access to none:
* display "no network access" during device configuration
* disable device "show config" option
> fix: handle devices with no network access

- web/src/shared/utils/downloadWGConfig.ts
The issue is described in more detail in #600.
fixes #600
Corresponding PR addressing this issue in the proxy can be found here: https://github.com/DefGuard/proxy/pull/62
> fix: add workaround for wrong config file extension on some browsers

- src/handlers/openid_flow.rs
Previously only the session existence and its expiration status was checked during the openid authorization, which is not enough, as the session is created before the MFA verification takes place.
> fix: verify mfa status during openid authorization

- src/grpc/desktop_client_mfa.rs
- src/grpc/enrollment.rs
- src/grpc/gateway.rs
- src/grpc/mod.rs
- src/grpc/password_reset.rs
- src/handlers/auth.rs
- src/handlers/ssh_authorized_keys.rs
- src/handlers/user.rs
- src/handlers/wireguard.rs
- src/handlers/worker.rs
- src/handlers/yubikey.rs
- adds more details to some logs
- adds more logging (info, debug, etc.)
All related PRs:
https://github.com/DefGuard/client/pull/239
https://github.com/DefGuard/defguard/pull/645
https://github.com/DefGuard/gateway/pull/98
closes #601
> Add more logging

- src/error.rs
- src/grpc/enrollment.rs
- src/handlers/mod.rs
- src/handlers/wireguard.rs
- tests/user.rs
- tests/wireguard.rs
Prevents user from submitting a device public key that already exists in the database. Current behavior (lack of such constraint) can cause problems, as we assume in multiple places that all devices have unique keys. This new constraint is enforced only on the API level, as enforcing it on the database at this time could break existing end user setups
> fix: prevent from adding duplicate public keys

- src/db/models/enrollment.rs
- templates/mail_enrollment_start.tera
> Fixes in the enrollment process

- migrations/20240809083720_add_licenses.down.sql
- migrations/20240809083720_add_licenses.up.sql
This PR adds license migrations necessary for #709. This PR has been separated to ease the development testing of #709, it will make switching dev instance images easier, without the issue of mismatched migration versions.
> Prepare the database for licenses

- web/src/components/AppLoader.tsx
Fetching the enterprise settings may happen on the login screen, when there is no session, resulting in a 401 response and a toast being displayed every time.
> fix: remove enterprise settings error toast

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/AddUserForm.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/style.scss
> add link to documentation

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/i18n/pl/index.ts
- web/src/pages/settings/components/LdapSettings/components/LdapSettingsForm.tsx
- web/src/pages/settings/components/LdapSettings/style.scss
- web/src/pages/settings/components/SmtpSettings/components/SmtpSettingsForm/SmtpSettingsForm.tsx
- web/src/pages/settings/components/SmtpSettings/components/SmtpSettingsForm/style.scss
> Unable to delete configuration for ldap and smtp when it is configured

- web/src/i18n/i18n-types.ts
- web/src/i18n/i18n-util.async.ts
- web/src/i18n/i18n-util.sync.ts
- web/src/i18n/i18n-util.ts
- web/src/i18n/ko/index.ts
Add Korean translation.
- "Groups Management" doesn't use typesafe-i18n right now. So, I skipped it like `en` and `pl` locales.
> Add korean translation

- .github/workflows/current.yml
fixes a missing "current" tag in the dev build images
> Fix current workflow

- Cargo.lock
- Cargo.toml
- src/grpc/mod.rs
- web/src/pages/allow/OpenidAllowPage.tsx
> Fix certificates for proxy communication and optional openid nonce issues

- Cargo.lock
- flake.lock
- src/enterprise/firewall.rs
Implement new firewall rule generation approach:
- each ACL translates to 2 rules - 1 ALLOW and 1 DENY
- allow rule determines who can access a destination
- deny rule drops all other traffic
> refactor firewall rule generation logic

- .sqlx/query-4dcd43e0b78c8948ffe3e9cc13c094bd2da10e535164bece43fe1f52945c8910.json
- .sqlx/query-7a1fd9a69b398f51efd5199aefb305d358693b0211cdb27b14b910a3515d501e.json
- .sqlx/query-b6e20a2b66be63641872b921a963bf0e9a25cab905322cc1ada5e03f1b5076c7.json
- src/enterprise/db/models/acl.rs
- src/enterprise/firewall.rs
Prevent adding all active users to explicitly specified allowed/denied users if allow/deny_all flag is enabled.
Also do the same for network devices.
> fix ACL info API response

- src/enterprise/db/models/acl.rs
- src/enterprise/firewall.rs
Change firewall config generator logic to create dedicated firewall rules for each alias instead of merging aliases with ACL destination.
> update firewall config generator to handle aliases

- src/enterprise/directory_sync/microsoft.rs
Previously when group names had quotes, the request to MS would fail. Quotes are escaped now according to the MS documentation.
> Escape quotes when querying MS groups

- flake.lock
- src/enterprise/firewall.rs
- src/lib.rs
- web/src/i18n/en/index.ts
- web/src/i18n/ko/index.ts
- web/src/i18n/pl/index.ts
Avoid creating allow-all firewall rules for ACLs which consist of only destination aliases.
resolves https://github.com/DefGuard/defguard/issues/1153 https://github.com/DefGuard/defguard/issues/1156
> fix alias-only rules handling

- Cargo.lock
- Cargo.toml
- src/db/models/user.rs
- src/enterprise/ldap/client.rs
- src/enterprise/ldap/mod.rs
- src/enterprise/ldap/utils.rs
- src/handlers/auth.rs
- adds more logs displayed during LDAP login process
- removes some redundant checks during LDAP login which may have previously prevented some users from logging in, the user login is now accepted if the user belongs to one of the sync groups in LDAP (if defined) and is active
- always marks user as coming from ldap if the LDAP login succeeds
> Fix LDAP login

- crates/defguard_core/src/db/models/audit_log/metadata.rs
- crates/defguard_core/src/db/models/audit_log/mod.rs
- crates/defguard_event_logger/src/lib.rs
- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/pages/activity/types.ts
Actually handle previously added VPN client events in the logger component.
> log VPN client events in audit log

- web/src/components/App/App.tsx
- web/src/components/Navigation/Navigation.tsx
Fixes permissions in the web UI to show the activity log page to normal (non-admin) users.
> show activity log to all users

- crates/defguard_core/src/grpc/gateway/client_state.rs
- crates/defguard_core/src/grpc/gateway/mod.rs
The endpoint we receive from gateway in wireguard peer stats updates includes a port, so it should actually be parsed as SocketAddr and only later converted to IpAddr
> fix how VPN client endpoint is parsed

- crates/defguard_core/src/db/models/user.rs
- crates/defguard_core/src/grpc/enrollment.rs
- fixes ACLs not updating on groups change https://github.com/DefGuard/defguard/issues/1188
- fixes ACLS not updating on user enrollment being completed https://github.com/DefGuard/defguard/issues/1236
> Fix ACL update edge cases

- crates/defguard_core/src/grpc/enrollment.rs
Send admin device management flag from enterprise settings to the proxy in enrollment start response.
Also actually validate this flag during device creation in enrollment process.
Related to https://github.com/DefGuard/proxy/issues/111
> Pass admin device management flag in enrollment start response

- crates/defguard_core/src/enterprise/activity_log_stream/activity_log_stream_manager.rs
Handle switching enterprise features from disabled to enabled. Also handle background task errors.
Resolves https://github.com/DefGuard/defguard/issues/1245
> fix enterprise feature check in activity log stream manager

- Cargo.lock
- crates/defguard_core/src/enterprise/db/models/acl.rs
- crates/defguard_core/src/enterprise/firewall.rs
- crates/defguard_core/src/enterprise/firewall/tests.rs
When preparing destination addrs for firewall rules we combine all the IPs, networks and IP ranges into non-overlapping IP ranges to avoid nftables errors since nftables don't accept overlapping elements.
Initially this meant that all networks got converted into ranges which caused issues with BSD packet filter which generates a separate rule for each IP in range. As a workaround we skipped converting networks into ranges, but this meant that we could no longer guarantee generated elements to be non-overlapping.
This PR introduces the ability to extract all possible subnets from generated ranges, thus resolving both of the above issues (networks are not needlessly turned into ranges and elements no longer overlap).
> fix IP address merging when generating firewall config from ACLs

- crates/defguard_core/src/db/models/device.rs
- crates/defguard_core/src/db/models/wireguard.rs
- crates/defguard_core/src/lib.rs
- crates/defguard_core/tests/integration/wireguard.rs
When updating network addresses, some of them may be left unchanged. Device IPs for those networks should not be recalculated and reassigned. This PR introduces the check and skips readdressing when appropriate.
> Avoid reassigning addresses for networks that didn't change

- web/src/i18n/en/index.ts
- web/src/i18n/i18n-types.ts
- web/src/pages/auth/Login/Login.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/AddUserForm/AddUserForm.tsx
- web/src/shared/hooks/api/api.ts
- web/src/shared/hooks/api/provider.tsx
Fixes axios provider not propagating error response due to middleware.
Fixes lack of error in add user form when typing already existing email into the form.
Related #1351 
Related #1345
> fix error propagarion from axios provider

- Cargo.lock
- crates/defguard_core/src/db/models/biometric_auth.rs
- crates/defguard_core/src/db/models/mod.rs
- crates/defguard_core/src/db/models/settings.rs
- crates/defguard_core/src/db/models/wireguard.rs
- crates/defguard_core/src/enterprise/activity_log_stream/activity_log_stream_manager.rs
- crates/defguard_core/src/enterprise/activity_log_stream/http_stream.rs
- crates/defguard_core/src/enterprise/ldap/mod.rs
- crates/defguard_core/src/grpc/client_mfa.rs
- crates/defguard_core/src/handlers/updates.rs
- crates/defguard_core/src/handlers/wireguard.rs
- crates/defguard_core/src/lib.rs
- crates/defguard_core/src/updates.rs
- crates/defguard_core/src/utility_thread.rs
- crates/defguard_event_router/src/lib.rs
- web/src/shared/hooks/api/api.ts
> Avoid HTTP return code: 204 No Content

- crates/defguard_core/templates/macros.tera
- web/package.json
- web/pnpm-lock.yaml
- web/src/pages/addDevice/utils/enrollmentToToken.ts
- web/src/pages/loader/style.scss
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/EnrollmentTokenCard/EnrollmentTokenCard.tsx
- web/src/pages/users/UsersOverview/modals/AddUserModal/components/EnrollmentTokenCard/style.scss
- web/src/shared/scss/base/_base.scss
> enrollment qr in enroll by admin modal

- web/src/pages/devices/modals/components/StandaloneDeviceModalForm/StandaloneDeviceModalForm.tsx
- web/src/pages/devices/modals/components/StandaloneDeviceModalForm/formSchema.ts
This is temp, proper fix should change API to properly inform UI about which IP's are reserved
Continued by #1399
> fix reserved ip form error not showing

- .github/workflows/build-docker.yml
- .github/workflows/ci.yml
- .github/workflows/current.yml
- .github/workflows/release.yml
- README.md
- flake.nix
Closes https://github.com/DefGuard/defguard/issues/1353
> sign Docker images using Cosign

- web/src/pages/activity-log/ActivityLogPage.tsx
- web/src/pages/devices/components/DevicesList/DevicesList.tsx
- web/src/pages/network/NetworkEditForm/NetworkEditForm.tsx
- web/src/pages/settings/components/GlobalSettings/types.ts
- web/src/shared/components/Layout/PageContainer/PageContainer.tsx
- web/src/shared/components/Layout/PageContainer/style.scss
- web/src/shared/components/Layout/PageLayout/PageLayout.tsx
- web/src/shared/scss/base/_base.scss
- web/src/shared/utils/displayDate.ts
Fixes #1348 
Fixes #1372 
Fixes #814 
Fixes #1374
> squash fixes

- crates/defguard_core/src/enterprise/ldap/mod.rs
- crates/defguard_core/src/enterprise/ldap/model.rs
- crates/defguard_core/src/enterprise/ldap/test_client.rs
- crates/defguard_core/src/enterprise/ldap/tests.rs
LDAP attribute names should be compared case insensitively, as this is how most LDAP implementations do it.
Fixes #1445
> Fix ldap attribute names case sensitive comparison

- crates/defguard_core/src/handlers/wireguard.rs
- crates/defguard_core/src/lib.rs
- crates/defguard_core/tests/integration/api/enterprise_settings.rs
title: User can bypass only_client_activation feature
ID: DG25-12
raport details: https://defguard.net/pentesting/
Restrict access to device management endpoints if `only_client_activation` setting is enabled.
Closes https://github.com/DefGuard/defguard/issues/1525
> Fixes pentest issue DG25-12 from 2025-09-02

- crates/defguard_core/src/handlers/wireguard.rs
- crates/defguard_core/src/lib.rs
- crates/defguard_core/tests/integration/api/enterprise_settings.rs
title: User can see configuration even when this option is not visible in GUI
ID: DG25-13
raport details: https://defguard.net/pentesting/
Restrict access to device config endpoint if `only_client_activation` setting is enabled.
Closes https://github.com/DefGuard/defguard/issues/1526
> Fixes pentest issue DG25-13 from 2025-09-02

- Dockerfile
Replace images with AWS-hosted ones to avoid DockerHub request limits.
> chore(CI): use AWS images in Dockerfile

- crates/defguard_core/src/grpc/password_reset.rs
- crates/defguard_core/src/grpc/utils.rs
- crates/defguard_core/src/handlers/mail.rs
- crates/defguard_core/src/handlers/user.rs
- crates/defguard_core/src/headers.rs
- crates/defguard_core/templates/base.tera
- title: HTML Injection - password reset
- ID: DG25-16
- raport details: https://defguard.net/pentesting/
Sanitize user-agent string during password reset process.
Partially resolves https://github.com/DefGuard/defguard/issues/1545
> Fixes pentest issue DG25-16 from 2025-09-02

- crates/defguard_core/Cargo.toml
- crates/defguard_core/src/db/models/mod.rs
- crates/defguard_core/src/grpc/enrollment.rs
- crates/defguard_core/src/grpc/utils.rs
- crates/defguard_core/src/handlers/user.rs
- crates/defguard_core/src/lib.rs
- title: Lack of server-side data validation during the enrollment process
- ID: DG25-10
- raport details: https://defguard.net/pentesting/
Validate user phone number during enrollment.
Related issue https://github.com/DefGuard/defguard/issues/1553
> Fixes pentest issue DG25-10 from 2025-09-02

- crates/defguard_core/src/db/models/oauth2client.rs
- crates/defguard_core/src/handlers/openid_flow.rs
- crates/defguard_core/tests/integration/api/openid.rs
- title: Open redirect
- ID: DG25-17
- report details: https://defguard.net/pentesting/
Don't allow open redirects when handling invalid openid authorization requests.
Related issue https://github.com/DefGuard/defguard/issues/1548
> Fixes pentest issue DG25-17 from 2025-09-02

- Cargo.lock
- crates/defguard_core/Cargo.toml
- crates/defguard_core/src/handlers/openid_clients.rs
- crates/defguard_core/tests/integration/api/openid.rs
- title: HTML Injection - OpenID login
- ID: DG25-21
- report details: https://defguard.net/pentesting/
Don't allow HTML in openid client app name.
Related issue https://github.com/DefGuard/defguard/issues/1551
> Fixes pentest issue DG25-21 from 2025-09-02

- .sqlx/query-27f3c5ea4443993df10ea337195635ad0e24e4855aa42cdceab2712f8c8dbef4.json
- Cargo.lock
- crates/defguard_core/src/db/models/auth_code.rs
- crates/defguard_core/src/db/models/oauth2client.rs
- crates/defguard_core/src/handlers/openid_flow.rs
- crates/defguard_core/tests/integration/api/common/client.rs
- crates/defguard_core/tests/integration/api/mod.rs
- crates/defguard_core/tests/integration/api/openid.rs
- crates/defguard_core/tests/integration/api/user.rs
- title: RFC 6749 violation - code can be used more than once due to race condition
- ID: DG25-24
- raport details: https://defguard.net/pentesting/
Consume auth code right away. Fixes #1550
> Fixes pentest issue DG25-24 from 2025-09-02

- crates/defguard_common/src/db/models/settings.rs
- crates/defguard_core/src/grpc/enrollment.rs
This pull request fixes vulnerabilities from penetration tests done by our security team on 2025-09-02:
title: Improper handling of user-provided input leads to panic
ID: DG25-11
raport details: https://defguard.net/pentesting/
Fall back to default enrollment email subject if it is somehow None. The field itself is indeed nullable, but it gets initialized on system startup so the issue would not occur under normal circumstances. 
Closes https://github.com/DefGuard/defguard/issues/1552
> Fixes pentest issue DG25-11 from 2025-09-02
